module.exports = {
  someSidebar: {
    "Getting Started": ['welcome'],
    "Resources": ['resources/formula-list'],
  },
  functionSideBar: {
    "Logical Functions": [
        "references/formulas/if",
        "references/formulas/and",
        "references/formulas/switch",
        "references/formulas/or",
        "references/formulas/not",
        "references/formulas/xor",
        "references/formulas/isnan",
    ],
    "Math Functions": [
        "references/formulas/sum",
        "references/formulas/average",
        "references/formulas/averageexzero",
        "references/formulas/averageexneg",
        "references/formulas/averageexzeroneg",
        "references/formulas/count",
        "references/formulas/abs",
        "references/formulas/min",
        "references/formulas/max",
        "references/formulas/power",
        "references/formulas/sqrt",
        "references/formulas/exp",
        "references/formulas/log",
    ],
    "Finance Functions": [
        "references/formulas/irr",
        "references/formulas/npv",
        "references/formulas/pmt",
        "references/formulas/ipmt",
        "references/formulas/fv",
        "references/formulas/pv",
        "references/formulas/cumipmt",
        "references/formulas/cumprinc",
        "references/formulas/rate",
    ],
    "Range Functions": [
        "references/formulas/range",
        "references/formulas/lastnperiods",
        "references/formulas/get",
        "references/formulas/foreach",
        "references/formulas/getrowvalue",
        "references/formulas/getcurrentrange",
        "references/formulas/findbyid",
        "references/formulas/findbytitle",
        "references/formulas/thisid",
        "references/formulas/thissourcekey",
    ],
    "Static Identifiers": [
        "references/formulas/this",
        "references/formulas/me",
        "references/formulas/current_series",
        "references/formulas/current_series_id",

        "references/formulas/current_period_index",
        "references/formulas/sim_from_to_index",
        "references/formulas/node-properties",
    ],
    "Additional Series": [
        "references/formulas/additional_series",

        "references/formulas/current_node_value",
        "references/formulas/node-properties",
    ],
},

};
